export const INPUT_AMOUNT_FROM   = "INPUT_AMOUNT_FROM"
export const INPUT_CURRENCY_FROM = "INPUT_CURRENCY_FROM"
export const OUTPUT_CURRENCY_TO  = "OUTPUT_CURRENCY_TO"
export const OUTPUT_AMOUNT_TO    = "OUTPUT_AMOUNT_TO"

export const CHANGE_CURRENCIES   = "CHANGE_CURRENCIES"

export const SET_GRAPH           = "SET_GRAPH"